sudo: true
language: ruby
ruby:
  - 2.3.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvirt-dev npm
bundler_args: --without development,mysql2,postgresql
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/settings.yaml.example config/settings.yaml
script:
  - npm i npm
  - node_modules/.bin/npm i
  - rake db:migrate
  - rake test
